server:
  port: 9050

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password
  application:
    name: graph-database-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true




