server:
  port: 9080

spring:
  application:
    name: advertising-search-service
  elasticsearch:
    uris: http://localhost:9200

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
