apiVersion: 1

datasources:
  # Elasticsearch (resource-usage indeks)
  - name: Elasticsearch
    type: elasticsearch
    uid: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    jsonData:
      index: "resource-usage"
      timeField: "date"
      esVersion: "8.14.3"
      logMessageField: ""
      logLevelField: ""

  # Elasticsearch (reservation-requests indeks)
  - name: Elasticsearch-Reservations
    type: elasticsearch
    uid: elasticsearch-reservations
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: "reservation-requests"
      timeField: "sent_date"
      esVersion: "8.14.3"
      logMessageField: ""
      logLevelField: ""

  # Neo4j (EventOrganisationService)
  - name: Neo4j
    type: kniepdennis-neo4j-datasource
    uid: neo4j
    access: proxy
    jsonData:
      url: bolt://neo4j:7687
      username: neo4j
    secureJsonData:
      password: password

  # InfluxDB (TimeSeriesAnalyticsService)
  - name: InfluxDB-TimeSeries
    type: influxdb
    uid: influxdb-timeseries
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: music-events-org
      defaultBucket: music_events_metrics
    secureJsonData:
      token: music-events-admin-token

  # Neo4j-Pricing (DynamicPricingService)
  - name: Neo4j-Pricing
    type: kniepdennis-neo4j-datasource
    uid: neo4j-pricing
    access: proxy
    jsonData:
      url: bolt://neo4j-pricing:7687
      username: neo4j
    secureJsonData:
      password: password

    # InfluxDB (NegotiationAnalyticsService)
  - name: InfluxDB-Negotiation
    type: influxdb
    uid: influxdb-negotiation
    access: proxy
    url: http://influxdb-negotiation:8086
    jsonData:
      version: Flux
      organization: nais_org
      defaultBucket: negotiation_bucket
    secureJsonData:
      token: my-super-secret-auth-token
 
  # Neo4j-Performer (PerformerManagementService)
  - name: Neo4j-Performer
    type: kniepdennis-neo4j-datasource
    uid: neo4j-performer
    access: proxy
    jsonData:
      url: bolt://neo4j-performer:7687
      username: neo4j
    secureJsonData:
      password: password
