server:
  port: 9090

spring:
  application:
    name: time-series-analytics-service
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:music-events-admin-token}
  org: ${INFLUXDB_ORG:music-events-org}
  bucket: ${INFLUXDB_BUCKET:music_events_metrics}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
