server:
  port: 9090

spring:
  application:
    name: negotiation-analytics-service
  influx:
    token: my-super-secret-auth-token
    bucket: negotiation_bucket
    org: nais_org
    url: http://influxdb:8086
    user: nais
    password: password
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
